sudo: required
dist: xenial
language: python

env:
  DOCKER_COMPOSE_VERSION: 1.23.1
  
services:
  - docker
  
before_install:
  - docker-compose -v
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  
script:
  - docker-compose up -d

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: raskal
  on:
    repo: BenjaminPalko/IoTHomeServer
    branch: develop

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

branches:
  only:
    - master
    - develop
    - benjamin
