services:
  - docker
 env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  # set env vars in the build settings to interact with repositories
  # see https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
  - docker-compose up -d docker .
branches:
  only:
    - master
    - develop
    - benjamin