services:
  - docker
 env:
  - DOCKER_COMPOSE_VERSION=1.4.2
before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
  - docker-compose up -d .
branches:
  only:
    - master
    - develop
    - benjamin